#!/usr/bin/env python3

"""
This script is intended to keep the total pile count in the "Previous Piles"
section up-to-date. You can run with no arguments, it will write out the total
number of piles.
"""

import os
import re

file_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'content', 'homepage', 'previous-piles.md')

with open(file_path) as testimonials:
    total = 0

    pattern = re.compile(r'- \d{4} \((\d+)')

    for line in testimonials:
        match = pattern.match(line)
        if match:
            total += int(match.group(1))

    print(f'There have been a total of {total} piles!')
